name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          git \
          python3-pip \
          openjdk-11-jdk \
          zip \
          unzip \
          zlib1g-dev \
          libssl-dev \
          libffi-dev \
          libc6-dev \
          libncurses5 \
          libstdc++6 \
          libffi-dev \
          libsqlite3-dev \
          aidl \
          libz-dev \
          libbz2-dev \
          liblzma-dev

    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install cython buildozer

    - name: Initialize Buildozer
      run: buildozer android clean

    - name: Build APK
      run: buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: FinancePro-Kivy-APK
        path: bin/*.apk
