name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          git \
          python3-pip \
          openjdk-11-jdk \
          zip \
          unzip \
          zlib1g-dev \
          libssl-dev \
          libffi-dev \
          libncurses5 \
          libsqlite3-dev \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev

        pip install --upgrade pip
        pip install cython
        pip install buildozer

    - name: Initialize Buildozer
      run: |
        buildozer init || true
        buildozer android clean

    - name: Build APK with Buildozer
      run: buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: FinanceBuddyApp-APK
        path: bin/*.apk
