name: Buildozer Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip \
            python3-setuptools \
            python3-dev \
            build-essential \
            git \
            unzip \
            zip \
            libssl-dev \
            libffi-dev \
            libsqlite3-dev \
            openjdk-11-jdk \
            wget \
            curl \
            libncurses5

      - name: Install Buildozer and dependencies
        run: |
          pip3 install --upgrade pip
          pip3 install buildozer cython

      - name: Initialize Buildozer (download android SDK/NDK etc.)
        run: buildozer android clean

      - name: Build APK
        run: buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk-debug
          path: bin/*.apk
