name: Build FinanceBuddy APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
      PATH: ${{ github.workspace }}/android-sdk/cmdline-tools/latest/bin:${{ github.workspace }}/android-sdk/platform-tools:${{ github.workspace }}/android-sdk/build-tools/34.0.0:$HOME/.local/bin:$PATH

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install system packages
      run: |
        sudo apt-get update
        sudo apt-get install -y tar unzip zip git openjdk-17-jdk python3 python3-pip \
          libffi-dev build-essential libssl-dev libbz2-dev libsqlite3-dev libncursesw6 curl

    - name: Install Python packages
      run: |
        python3 -m pip install --upgrade pip
        pip install --user buildozer cython

    - name: Setup Android SDK cmdline tools
      run: |
        mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
        cd $ANDROID_SDK_ROOT/cmdline-tools
        curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
        unzip -q commandlinetools.zip
        rm commandlinetools.zip
        mv cmdline-tools latest

    - name: Accept licenses and install SDK components
      run: |
        yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses
        sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools" "platforms;android-34" "build-tools;34.0.0" "ndk;25.2.9519653" "cmake;3.22.1"

    - name: Clean old builds (optional but recommended)
      run: buildozer android clean || true

    - name: Build Android APK
      run: buildozer -v android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: FinanceBuddy-debug-apk
        path: bin/*.apk
