name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          git \
          python3-pip \
          openjdk-11-jdk \
          zip unzip \
          libffi-dev \
          libssl-dev \
          libncurses5 \
          libjpeg-dev \
          libfreetype6-dev \
          libgl1-mesa-dev \
          libgles2-mesa-dev \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          libbz2-dev \
          libsqlite3-dev

        pip install --upgrade pip
        pip install cython virtualenv
        pip install buildozer

    - name: Accept Android SDK licenses manually
      run: |
        mkdir -p ~/.android && touch ~/.android/repositories.cfg
        yes | sdkmanager --licenses || true

    - name: Set JAVA_HOME
      run: echo "JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64" >> $GITHUB_ENV

    - name: Initialize Buildozer
      run: |
        if [ ! -f buildozer.spec ]; then
          buildozer init
        fi

        sed -i 's/^android.api =.*/android.api = 34/' buildozer.spec
        sed -i 's/^# android.minapi =.*/android.minapi = 21/' buildozer.spec
        sed -i 's/^# android.sdk =.*/android.sdk = 34/' buildozer.spec
        sed -i 's/^# android.ndk =.*/android.ndk = 25b/' buildozer.spec
        sed -i 's/^# android.accept_sdk_license =.*/android.accept_sdk_license = True/' buildozer.spec

    - name: Build APK
      run: |
        buildozer android clean
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: FinanceBuddyApp-APK
        path: bin/*.apk
