name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: ${{ runner.temp }}/android-sdk

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk python3-pip python3-setuptools python3-wheel unzip wget tar libncurses6

    - name: Setup Android SDK Command-line Tools
      run: |
        mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
        cd $ANDROID_SDK_ROOT/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-10125497_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip
        mv cmdline-tools latest
        rm cmdline-tools.zip

    - name: Update PATH for Android SDK tools
      shell: bash
      run: |
        echo "export ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
        echo "export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH" >> $GITHUB_ENV
      # Note: We export env vars to $GITHUB_ENV for subsequent steps

    - name: Accept Android SDK licenses and install packages
      shell: bash
      run: |
        export ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT
        export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2" "ndk;25.2.9519653" "cmdline-tools;latest" "platforms;android-21" "platforms;android-31" "build-tools;31.0.0" "extras;google;m2repository" "extras;android;m2repository" "aidl"

    - name: Install Buildozer and dependencies via pip
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install buildozer cython

    - name: Build APK with Buildozer
      shell: bash
      run: |
        export ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT
        export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH
        buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: apk
        path: bin/*.apk
